services:
        webserver:
                build: .
                environment:
                        BACKEND_API_BASE_URL: ${BACKEND_API_BASE_URL}
                ports:
                        - "${PORT}:${PORT}"
