services:
        webserver:
                build:
                        context: .
                        args:
                                VITE_WEBSERVER_API_BASE_URL: ${VITE_WEBSERVER_API_BASE_URL}
                environment:
                        WEBSERVER_PORT: ${WEBSERVER_PORT}
                ports:
                        - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
